import {
  FlaskConical,
  Pill,
  Plus,
  ScanLine,
  Stethoscope,
  Syringe,
} from 'lucide-react';
import type { EncounterWorkspaceSectionTheme } from './encounter-workspace-types';

export const ENCOUNTER_WORKSPACE_SECTION_THEMES: Record<
  'prescription' | 'lab' | 'radiology' | 'procedure' | 'referral',
  EncounterWorkspaceSectionTheme
> = {
  prescription: {
    icon: Pill,
    title: 'الوصفة الطبية',
    iconWrapClass: 'bg-[#EFF6FF]',
    iconClass: 'text-[#2563EB]',
    borderClass: 'border-[#BFDBFE]',
    headerClass: 'bg-[#F8FBFF]',
    panelClass: 'bg-[#F8FBFF]',
    countClass: 'border-[#93C5FD] text-[#2563EB]',
    footerDotClass: 'bg-[#2563EB]',
    statusDraftClass: 'bg-[#FEF3C7] text-[#B45309]',
    statusApprovedClass: 'bg-[#DCFCE7] text-[#15803D]',
    statusEmptyClass: 'bg-[#F2F4F7] text-[#667085]',
  },
  lab: {
    icon: FlaskConical,
    title: 'طلبات التحاليل',
    iconWrapClass: 'bg-[#F5F3FF]',
    iconClass: 'text-[#7C3AED]',
    borderClass: 'border-[#DDD6FE]',
    headerClass: 'bg-[#FAF5FF]',
    panelClass: 'bg-[#FAF5FF]',
    countClass: 'border-[#C4B5FD] text-[#7C3AED]',
    footerDotClass: 'bg-[#7C3AED]',
    statusDraftClass: 'bg-[#FEF3C7] text-[#B45309]',
    statusApprovedClass: 'bg-[#DCFCE7] text-[#15803D]',
    statusEmptyClass: 'bg-[#F2F4F7] text-[#667085]',
  },
  radiology: {
    icon: ScanLine,
    title: 'طلبات الأشعة',
    iconWrapClass: 'bg-[#ECFDF3]',
    iconClass: 'text-[#16A34A]',
    borderClass: 'border-[#BBF7D0]',
    headerClass: 'bg-[#F0FDF4]',
    panelClass: 'bg-[#F0FDF4]',
    countClass: 'border-[#86EFAC] text-[#16A34A]',
    footerDotClass: 'bg-[#16A34A]',
    statusDraftClass: 'bg-[#FEF3C7] text-[#B45309]',
    statusApprovedClass: 'bg-[#DCFCE7] text-[#15803D]',
    statusEmptyClass: 'bg-[#F2F4F7] text-[#667085]',
  },
  procedure: {
    icon: Syringe,
    title: 'طلبات الإجراءات',
    iconWrapClass: 'bg-[#FFF7ED]',
    iconClass: 'text-[#EA580C]',
    borderClass: 'border-[#FED7AA]',
    headerClass: 'bg-[#FFFBEB]',
    panelClass: 'bg-[#FFFBEB]',
    countClass: 'border-[#FDBA74] text-[#EA580C]',
    footerDotClass: 'bg-[#EA580C]',
    statusDraftClass: 'bg-[#FEF3C7] text-[#B45309]',
    statusApprovedClass: 'bg-[#DCFCE7] text-[#15803D]',
    statusEmptyClass: 'bg-[#F2F4F7] text-[#667085]',
  },
  referral: {
    icon: Stethoscope,
    title: 'تحويلات طبية',
    iconWrapClass: 'bg-[#E6F4F3]',
    iconClass: 'text-primary',
    borderClass: 'border-[#9EE8E0]',
    headerClass: 'bg-[#F0FAF9]',
    panelClass: 'bg-[#F0FAF9]',
    countClass: 'border-[#9EE8E0] text-primary',
    footerDotClass: 'bg-primary',
    statusDraftClass: 'bg-[#FEF3C7] text-[#B45309]',
    statusApprovedClass: 'bg-[#DCFCE7] text-[#15803D]',
    statusEmptyClass: 'bg-[#F2F4F7] text-[#667085]',
  },
};

export const ENCOUNTER_WORKSPACE_ADD_ICON = Plus;
