import type { DoctorActivityLogItem } from '@/lib/doctor/activityLog/types';

export const MOCK_DOCTOR_ACTIVITY_LOGS: DoctorActivityLogItem[] = [
  {
    id: 'ACT-001',
    title: 'تمت مشاهدة سجلك الطبي بواسطة د. خالد الشمري',
    timestamp: '2026-02-16T10:00:00.000Z',
    actionType: 'view_record',
    dateLabel: '20 ديسمبر',
    timeLabel: '2:30 PM',
    patientName: 'خالد عبدالله الشمري',
    operationTypeLabel: 'عرض سجل',
    ip: '192.168.1.1',
    device: 'iPhone',
  },
  {
    id: 'ACT-002',
    title: 'تم رفع ملف طبي جديد إلى سجل المريض',
    timestamp: '2026-02-15T14:20:00.000Z',
    actionType: 'upload_file',
    dateLabel: '19 ديسمبر',
    timeLabel: '11:15 AM',
    patientName: 'سارة علي',
    operationTypeLabel: 'رفع ملف',
    ip: '192.168.1.24',
    device: 'Chrome / Windows',
  },
  {
    id: 'ACT-003',
    title: 'تم تسجيل الدخول إلى حسابك بنجاح',
    timestamp: '2026-02-15T08:05:00.000Z',
    actionType: 'login',
    dateLabel: '19 ديسمبر',
    timeLabel: '8:05 AM',
    operationTypeLabel: 'تسجيل دخول',
    ip: '192.168.1.10',
    device: 'Safari / macOS',
  },
  {
    id: 'ACT-004',
    title: 'تم تحديث بيانات الملف الشخصي',
    timestamp: '2026-02-14T16:45:00.000Z',
    actionType: 'update_profile',
    dateLabel: '18 ديسمبر',
    timeLabel: '4:45 PM',
    operationTypeLabel: 'تحديث ملف',
    ip: '192.168.1.10',
    device: 'Chrome / Windows',
  },
  {
    id: 'ACT-005',
    title: 'تمت الموافقة على طلب وصول إلى سجل مريض',
    timestamp: '2026-02-14T09:30:00.000Z',
    actionType: 'access_request',
    dateLabel: '18 ديسمبر',
    timeLabel: '9:30 AM',
    patientName: 'محمد خالد',
    operationTypeLabel: 'طلب وصول',
    ip: '192.168.1.55',
    device: 'Android',
  },
];

export const ACTIVITY_LOG_INFO_TEXT =
  'يتم تسجيل جميع عمليات الوصول إلى السجلات الطبية والبيانات الحساسة لضمان الأمان والامتثال القانوني. يمكنك مراجعة هذه السجلات في أي وقت.';
